### ISSUE TITLE
Hidden triumphs cause the widget to crash

### ISSUE THREAD

**Issue by vzsg** [joshhunt/GhostOverlay#15]
Hey, thanks for this really awesome widget!

It's been working really well for me, with a small hickup I noticed today with version 1.2.3.0. (Latest OS, shouldn't be relevant.)

With season 11, some new, hidden triumphs have been added to the lineup, and every time I tried to load up a category that has one, the widget crashes.

For example, see:
- Triumphs -> Exotic Catalysts -> Energy weapons
- Triumphs -> (Seasonal) Activities -> Season 11.

**Comment by joshhunt** [comment]
Yup, this’ll be fixed next week

**Comment by joshhunt** [comment]
Annoyingly I have a fix for this which has passed certification, but I have to resubmit a new build because Microsoft delayed their update to Xbox Game Bar which the new version requires. Will be resubmitting a new build today, which should be out shortly.

I'm going to close this ticket because I've fixed it in dev, and it'll be release "soon" :)

**Comment by vzsg** [comment]
Thank you!
